name: hipSYCL test

on: [push]

jobs:
  test-with-hipsycl:
    name: Run tests with hipSYCL
    strategy:
      matrix:
        clang_version: [13]
        rocm_version: ['5.1.1']
        os: [ubuntu-20.04]
        cuda: [11.0]
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: install ROCm
      run: |
        sudo apt install libnuma-dev cmake unzip
        wget -q -O - https://repo.radeon.com/rocm/rocm.gpg.key | sudo apt-key add -
        echo 'deb [arch=amd64] https://repo.radeon.com/rocm/apt/${{matrix.rocm_version}}/ ubuntu main' | sudo tee /etc/apt/sources.list.d/rocm.list
        sudo apt update
        sudo apt install rocm-dev
